### ISSUE TITLE
Addition of an extra state so that it behaves as a tri state switch

### ISSUE THREAD

**Issue by vjr12** [danielarias123/react-multi-toggle#13]
Want to implement something like a switch that has three states, "ENABLED,PENDING,DISABLED" . Is it possible that something like this can be implemented

Something like this?
![Screenshot from 2019-08-13 17-14-01](https://user-images.githubusercontent.com/42905121/62939069-037e8480-bdee-11e9-8ca4-28d3df4ec6d7.png)

![Screenshot from 2019-08-13 17-16-48](https://user-images.githubusercontent.com/42905121/62939143-332d8c80-bdee-11e9-84a7-ea3594eb23e5.png)

![Screenshot from 2019-08-13 17-16-35](https://user-images.githubusercontent.com/42905121/62939174-404a7b80-bdee-11e9-8cbf-a724020b4571.png)

**Comment by ChristianMurphy** [comment]
@velsonjr start with something like: https://codesandbox.io/s/hidden-microservice-17cfq and style it to suite your needs.

:notebook: this also can resolve https://github.com/gfazioli/react-toggle/issues/17, https://github.com/markusenglund/react-switch/issues/52, https://github.com/aaronshaf/react-toggle/issues/138, https://github.com/ItsAsbreuk/itsa-react-togglebutton/issues/1, and https://spectrum.chat/react/help/custom-component-for-a-switch-with-off-pending-on-state-reactjs~02599d24-9098-4255-b3e4-610d74d4f777

**Comment by velsonjr** [comment]
@ChristianMurphy How do you add "optionClass" property?

**Comment by ChristianMurphy** [comment]
The way it's documented in the readme.
See the example in https://spectrum.chat/react/help/custom-component-for-a-switch-with-off-pending-on-state-reactjs~02599d24-9098-4255-b3e4-610d74d4f777

@velsonjr please be respectful of open source maintainers time, we're helping folks for free, often on personal time.
Posting the same question in multiple places: requires duplicate effort to answer, wastes time, and can be frustrating.
