### ISSUE TITLE
Label propType is string

### ISSUE THREAD

**Issue by liviuignat** [danielarias123/react-multi-toggle#2]
Having a label with `PropTypes.string` will create some limitations. 

For example when using labels as other components:
- `Icon` as label
- `FormattedMessage` (from react-intl) will create a `<span />`

**Comment by danielarias123** [comment]
@liviuignat Good call! This has been fixed in https://github.com/danielarias123/react-multi-toggle/commit/35c86b2ec08ca53b2e4aba933ac2fb4e225edb29. Thanks!
